SELECT UGU.USER_ID, 
       UGU.NICKNAME, 
       CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS '전체주소', 
       CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', SUBSTR(UGU.TLNO, 8)) AS '전화번호'
FROM USED_GOODS_USER UGU
JOIN (
    SELECT UGU1.USER_ID AS USER_ID, COUNT(*) AS COUNT
    FROM USED_GOODS_USER UGU1
    JOIN USED_GOODS_BOARD UGB
    ON UGU1.USER_ID = UGB.WRITER_ID
    GROUP BY UGU1.USER_ID
) AS UGU2
ON UGU.USER_ID = UGU2.USER_ID AND UGU2.COUNT >= 3
ORDER BY UGU.USER_ID DESC


