SELECT ITI.ITEM_ID, ITI.ITEM_NAME, ITI.RARITY
FROM ITEM_INFO ITI
WHERE ITEM_ID IN (
    SELECT IT.ITEM_ID
    FROM ITEM_TREE IT
    JOIN (
        SELECT ITEM_ID
        FROM ITEM_INFO 
        WHERE RARITY = 'RARE'
    ) II
    ON IT.PARENT_ITEM_ID = II.ITEM_ID
)
ORDER BY ITI.ITEM_ID DESC;