SELECT ITEMI.ITEM_ID, ITEMI.ITEM_NAME, ITEMI.RARITY
FROM ITEM_INFO ITEMI
WHERE ITEMI.ITEM_ID IN (
    SELECT ITT.ITEM_ID
    FROM ITEM_TREE ITT 
    JOIN ITEM_INFO ITI
    ON ITI.ITEM_ID = ITT.PARENT_ITEM_ID
    WHERE ITI.RARITY = 'RARE'
)
ORDER BY ITEMI.ITEM_ID DESC