SELECT DISTINCT ITI01.ITEM_ID, ITI01.ITEM_NAME, ITI01.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO ITI01 ON IT.ITEM_ID = ITI01.ITEM_ID
JOIN ITEM_INFO ITI02 ON IT.PARENT_ITEM_ID = ITI02.ITEM_ID
WHERE ITI02.RARITY = 'RARE'
ORDER BY ITI01.ITEM_ID DESC;