SELECT YEAR(DIFFERENTIATION_DATE)AS YEAR, E2.MV - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E1
JOIN  (
 SELECT YEAR(DIFFERENTIATION_DATE)AS YEAR, MAX(SIZE_OF_COLONY)AS MV
 FROM ECOLI_DATA
 GROUP BY YEAR(DIFFERENTIATION_DATE)
) E2
ON YEAR(DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR, YEAR_DEV;