SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE DATE_FORMAT(CRCRH.START_DATE, '%m') LIKE '10' AND CRCC.CAR_TYPE LIKE '세단'
ORDER BY CRCC.CAR_ID DESC