WITH MAX_FISH AS (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO
    WHERE
        LENGTH IS NOT NULL
    GROUP BY
        FISH_TYPE
)
SELECT
    FI.ID,
    FNI.FISH_NAME,
    FI.LENGTH
FROM
    FISH_INFO FI
JOIN
    MAX_FISH MF
    ON FI.FISH_TYPE = MF.FISH_TYPE AND FI.LENGTH = MF.MAX_LENGTH
JOIN
    FISH_NAME_INFO FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY
    FI.ID;
