SELECT U1.TITLE, U1.BOARD_ID, U2.REPLY_ID, U2.WRITER_ID, U2.CONTENTS, DATE_FORMAT (U2.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD U1
INNER JOIN USED_GOODS_REPLY U2
ON U1.BOARD_ID = U2.BOARD_ID
WHERE YEAR(U1.CREATED_DATE) = 2022 AND MONTH(U1.CREATED_DATE) = 10
ORDER BY U2.CREATED_DATE ASC, U1.TITLE ASC