


SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UGF
JOIN (
        SELECT UGB1.BOARD_ID
        FROM USED_GOODS_BOARD UGB1
        WHERE VIEWS IN (
            SELECT MAX(UGB2.VIEWS)
            FROM USED_GOODS_BOARD UGB2
        ) 
    ) UGB
ON UGF.BOARD_ID = UGB.BOARD_ID
ORDER BY UGF.FILE_ID DESC




