


SELECT COUNT(*) AS FISH_COUNT, MAX(FI2.LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO FI1
JOIN (
    SELECT ID,
        CASE 
            WHEN LENGTH <= 10 THEN 10
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END AS LENGTH
    FROM FISH_INFO
) AS FI2
ON FI1.ID = FI2.ID
GROUP BY FI1.FISH_TYPE
HAVING AVG(FI2.LENGTH) >= 33
ORDER BY FISH_TYPE